# https://gohugo.io/getting-started/configuration/

title: Text Consulting Group
description: Text와 Code를 씁니다.
url: textconsulting.io

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

build:
  writeStats: true

disableKinds:
- taxonomy
- term
