# https://gohugo.io/content-management/menus/#params
# identifier params for header scrolling
main:
- name: Home
  url: /
  weight: -110

button:
- name: t.TCG
  url: https://t.textconsulting.io
  weight: -100
- name: team-durumi
  url: https://github.com/team-durumi
  weight: -90
- name: Airbnb
  url: https://airbnb.com/h/tcg-home
  weight: -80 
