# https://gohugo.io/content-management/menus/#params
# identifier params for header scrolling
main:
- name: 홈
  url: /
  weight: -110
- name: 아이템
  url: /items
  weight: -100
- name: 컬렉션
  url: 
  weight: -90
- name: 태그
  url: /tags/
  weight: 6
  parent: 컬렉션
- name: 생산자
  url: /creators/
  weight: 2
  parent: 컬렉션     
- name: 주제
  url: /subjects/
  weight: 3
  parent: 컬렉션     
- name: 출처
  url: /sources/
  weight: 4
  parent: 컬렉션 
- name: 장소
  url: /venues/
  parent: 컬렉션
  weight: 5
  

button:
- name: t.TCG
  url: https://t.textconsulting.io
  weight: -100
- name: team-durumi
  url: https://github.com/team-durumi
  weight: -90