title: TCG
description: Text Consulting Group
images:
  - site-feature-image.jpg

license:
  title_of_work: TCG
  link_to_work: Github.com/woonjjang
  createor_of_work: woonjjang
  link_to_creator_profile: Github.com/woonjjang
  year_of_creation: 2022
